import MainSideBar from "@/components/SideBar/Layout/MainSideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="bg-[#F4F5FA] custom-width">
        <MainSideBar>{children}</MainSideBar>
      </body>
    </html>
  );
}
