import MainSideBar from "@/components/SideBar/Layout/MainSideBar";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <MainSideBar>{children}</MainSideBar>;
}
